public class ViaCepModel {

    @AuraEnabled 
    public String cep;
    @AuraEnabled 
    public String logradouro;
    @AuraEnabled
    public String complemento;
    @AuraEnabled
    public String bairro;
    @AuraEnabled
    public String localidade;
    @AuraEnabled
    public String uf;
    @AuraEnabled
    public string ibge;
    @AuraEnabled
    public string gia;
    @AuraEnabled
    public String ddd;
    @AuraEnabled
    public String siafi;
}